
node {
        def templateName = 'gitbook-centos-docker'

        stage('test') {
          sh 'oc get bc'
        }

        stage('build') {
                openshift.withCluster() {
                    openshift.withProject() {
                      def builds = openshift.startBuild("${gitbook-centos-docker}")
                      timeout(5) { 
                        builds.untilEach {
                          return it.object().status.phase == "Complete"
                        }
                      }
                    }
                }
        }

        stage('deploy') {
                openshift.withCluster() {
                    openshift.withProject() {
                      def rm = openshift.selector("dc", templateName).rollout()
                      timeout(5) { 
                        openshift.selector("dc", templateName).related('pods').untilEach(1) {
                          return (it.object().status.phase == "Running")
                        }
                      }
                    }
                }
        }

        stage('ask for promotion') {
            input id: 'Approve01', message: 'Wanna push to prod?????', ok: 'HANG TIGHT!'
        }

        stage('tag and promote') {
                openshift.withCluster() {
                    openshift.withProject() {
                      openshift.tag("${templateName}:latest", "${templateName}:prod") 
                    }
                }
        }
}