
node {
    def templateName = 'gitbook-centos-docker'

    openshift.withCluster() {
        openshift.withProject() {

            stage('build') {
                def builds = openshift.startBuild("${templateName}")
                timeout(5) { 
                  builds.untilEach(1) {
                    return it.object().status.phase == "Complete"
                  }
                  builds.logs('-f')
                }
            }

            stage('deploy') {
                def dc = openshift.selector('dc', "${templateName}")
                dc.rollout().status()
            }

            stage('ask for promotion') {
                input id: 'Approve01', message: 'Wanna push to prod?????', ok: 'HANG TIGHT!'
            }

            stage('tag and promote') {
                openshift.tag("${templateName}:latest", "${templateName}:prod") 
            }
        }
    }
}