
node {
        def templateName = 'gitbook-centos-docker'
        def devProject = 'dev-gitbook'
        def prodProject = 'prod-gitbook'

        stage('build') {
                openshift.withCluster() {
                    openshift.withProject("${devProject}") {
                      def builds = openshift.selector("bc", templateName).related('builds')
                      timeout(5) { 
                        builds.untilEach(1) {
                          return it.object().status.phase == "Complete"
                        }
                      }
                    }
                }
        }

        stage('deploy') {
                openshift.withCluster() {
                    openshift.withProject("${devProject}") {
                      def rm = openshift.selector("dc", templateName).rollout()
                      timeout(5) { 
                        openshift.selector("dc", templateName).related('pods').untilEach(1) {
                          return (it.object().status.phase == "Running")
                        }
                      }
                    }
                }
        }

        stage('ask for promotion') {
            input id: 'Approve01', message: 'Wanna push to prod?????', ok: 'HANG TIGHT!'
        }

        stage('tag and promote') {
                openshift.withCluster() {
                    openshift.withProject("${devProject}") {
                      openshift.tag("${templateName}:latest", "${templateName}:prod") 
                    }
                }
        }
}